# Makefile.in generated by automake 1.15 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2014 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/gpuminer
pkgincludedir = $(includedir)/gpuminer
pkglibdir = $(libdir)/gpuminer
pkglibexecdir = $(libexecdir)/gpuminer
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-pc-linux-gnu
host_triplet = x86_64-pc-linux-gnu
target_triplet = x86_64-pc-linux-gnu
bin_PROGRAMS = gpuminer$(EXEEXT)
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/boost.m4 \
	$(top_srcdir)/m4/libtool.m4 $(top_srcdir)/m4/ltoptions.m4 \
	$(top_srcdir)/m4/ltsugar.m4 $(top_srcdir)/m4/ltversion.m4 \
	$(top_srcdir)/m4/lt~obsolete.m4 $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = gpuminer-config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am__dirstamp = $(am__leading_dot)dirstamp
am_gpuminer_OBJECTS = gpuminer-bigmath.$(OBJEXT) \
	gpuminer-miner.$(OBJEXT) gpuminer-prime.$(OBJEXT) \
	gpuminer-util.$(OBJEXT) gpuminer-iniParser.$(OBJEXT) \
	cuda/sieve.$(OBJEXT) \
  cuda/fermat.$(OBJEXT) \
	hash/gpuminer-KeccakDuplex.$(OBJEXT) \
	hash/gpuminer-skein.$(OBJEXT) \
	hash/gpuminer-Keccak-compact64.$(OBJEXT) \
	hash/gpuminer-KeccakHash.$(OBJEXT) \
	hash/gpuminer-KeccakSponge.$(OBJEXT) \
	hash/gpuminer-skein_block.$(OBJEXT)
gpuminer_OBJECTS = $(am_gpuminer_OBJECTS)
am__DEPENDENCIES_1 =
gpuminer_DEPENDENCIES = $(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1) $(am__DEPENDENCIES_1)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
gpuminer_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(gpuminer_LDFLAGS) $(LDFLAGS) -o $@
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
SOURCES = $(gpuminer_SOURCES)
DIST_SOURCES = $(gpuminer_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)gpuminer-config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/gpuminer-config.h.in \
	AUTHORS COPYING ChangeLog INSTALL NEWS README compile \
	config.guess config.sub depcomp install-sh ltmain.sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = aclocal-1.15
ALLOCA = 
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AR = ar
AUTOCONF = autoconf
AUTOHEADER = autoheader
AUTOMAKE = automake-1.15
AWK = gawk
BOOST_CPPFLAGS =  -pthread
BOOST_FILESYSTEM_LDFLAGS = 
BOOST_FILESYSTEM_LDPATH = 
BOOST_FILESYSTEM_LIBS = -lboost_filesystem
BOOST_LDPATH = 
BOOST_PROGRAM_OPTIONS_LDFLAGS = 
BOOST_PROGRAM_OPTIONS_LDPATH = 
BOOST_PROGRAM_OPTIONS_LIBS = -lboost_program_options
BOOST_ROOT = 
BOOST_SYSTEM_LDFLAGS = 
BOOST_SYSTEM_LDPATH = 
BOOST_SYSTEM_LIBS = -lboost_system
BOOST_THREAD_LDFLAGS = 
BOOST_THREAD_LDPATH = 
BOOST_THREAD_LIBS = -lboost_thread -lboost_system -pthread 
CC = gcc
CCAS = gcc
CCASDEPMODE = depmode=gcc3
CCASFLAGS = -g -O2
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CUDA_CFLAGS = -I/usr/local/cuda/include
CUDA_LDFLAGS = -L/usr/local/cuda/lib64
CUDA_LIBS = -lcudadevrt -lcudart -static-libstdc++
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DISTCHECK_CONFIGURE_FLAGS =  '--with-boost='
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FGREP = /bin/grep -F
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LIBOBJS = 
LIBS = -lprimesieve -lgmp -lcrypto -lssl 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
LT_SYS_LIBRARY_PATH = 
MAINT = #
MAKEINFO = makeinfo
MANIFEST_TOOL = :
MKDIR_P = /bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
NVCC = nvcc
OBJDUMP = objdump
OBJEXT = o
OPENMP_CFLAGS = -fopenmp
OTOOL = 
OTOOL64 = 
PACKAGE = gpuminer
PACKAGE_BUGREPORT = 
PACKAGE_NAME = gpuminer
PACKAGE_STRING = gpuminer 2014.10.09
PACKAGE_TARNAME = gpuminer
PACKAGE_URL = 
PACKAGE_VERSION = 2014.10.09
PATH_SEPARATOR = :
PTHREAD_FLAGS = -pthread
PTHREAD_LIBS = -lpthread
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
STRIP = strip
VERSION = 2014.10.09
abs_builddir = /home/blackjack/Desktop/PrimeSoloGPUMiner-master
abs_srcdir = /home/blackjack/Desktop/PrimeSoloGPUMiner-master
abs_top_builddir = /home/blackjack/Desktop/PrimeSoloGPUMiner-master
abs_top_srcdir = /home/blackjack/Desktop/PrimeSoloGPUMiner-master
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-pc-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-pc-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/blackjack/Desktop/PrimeSoloGPUMiner-master/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target = x86_64-pc-linux-gnu
target_alias = 
target_cpu = x86_64
target_os = linux-gnu
target_vendor = pc
top_build_prefix = 
top_builddir = .
top_srcdir = .
ACLOCAL_AMFLAGS = -I m4
EXTRA_DIST = autogen.sh README.txt LICENSE.txt \
			  compat/gettimeofday.c compat/getopt/getopt_long.c gpuminer-config.h.in

gpuminer_SOURCES = bigmath.cpp  miner.cpp  prime.cpp  util.cpp \
			   bigmath.h bignum.h core.h types.h util.h \
			   iniParser.cpp \
			   cuda/sieve.cu cuda/fermat.cu cuda/fermat.h cuda/frame_resources.h cuda/cuda.h \
			   hash/brg_endian.h  hash/crypto_hash.h       hash/KeccakDuplex.c  hash/KeccakF-1600-interface.h  hash/KeccakHash.h    hash/KeccakSponge.h   hash/skein.cpp  hash/skein_iv.h    hash/templates.h \
			   hash/brg_types.h   hash/Keccak-compact64.c  hash/KeccakDuplex.h  hash/KeccakHash.c              hash/KeccakSponge.c  hash/skein_block.cpp  hash/skein.h    hash/skein_port.h  hash/uint1024.h

gpuminer_LDFLAGS = $(PTHREAD_FLAGS) -L/usr/local/cuda/lib64 $(BOOST_LDFLAGS) $(BOOST_FILESYSTEM_LDFLAGS) $(BOOST_SYSTEM_LDFLAGS) $(BOOST_THREAD_LDFLAGS) $(BOOST_PROGRAM_OPTIONS_LDFLAGS)
gpuminer_LDADD = -lpthread -lcudadevrt -lcudart -static-libstdc++ -fopenmp -lprimesieve -lgmp -lcrypto -lssl  -lcuda -lgmp -lprimesieve $(BOOST_FILESYSTEM_LIBS) $(BOOST_SYSTEM_LIBS) $(BOOST_THREAD_LIBS) $(BOOST_PROGRAM_OPTIONS_LIBS)
gpuminer_CPPFLAGS = -std=c++0x -msse2 -fopenmp $(PTHREAD_FLAGS) $(BOOST_CPPFLAGS) -fno-strict-aliasing
all: gpuminer-config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .cpp .cu .lo .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in: # $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure: # $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4): # $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

gpuminer-config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/gpuminer-config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status gpuminer-config.h
$(srcdir)/gpuminer-config.h.in: # $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f gpuminer-config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	 || test -f $$p1 \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
cuda/$(am__dirstamp):
	@$(MKDIR_P) cuda
	@: > cuda/$(am__dirstamp)
cuda/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) cuda/$(DEPDIR)
	@: > cuda/$(DEPDIR)/$(am__dirstamp)
cuda/sieve.$(OBJEXT): cuda/$(am__dirstamp) \
	cuda/$(DEPDIR)/$(am__dirstamp)
cuda/fermat.$(OBJEXT): cuda/$(am__dirstamp) \
	cuda/$(DEPDIR)/$(am__dirstamp)
hash/$(am__dirstamp):
	@$(MKDIR_P) hash
	@: > hash/$(am__dirstamp)
hash/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) hash/$(DEPDIR)
	@: > hash/$(DEPDIR)/$(am__dirstamp)
hash/gpuminer-KeccakDuplex.$(OBJEXT): hash/$(am__dirstamp) \
	hash/$(DEPDIR)/$(am__dirstamp)
hash/gpuminer-skein.$(OBJEXT): hash/$(am__dirstamp) \
	hash/$(DEPDIR)/$(am__dirstamp)
hash/gpuminer-Keccak-compact64.$(OBJEXT): hash/$(am__dirstamp) \
	hash/$(DEPDIR)/$(am__dirstamp)
hash/gpuminer-KeccakHash.$(OBJEXT): hash/$(am__dirstamp) \
	hash/$(DEPDIR)/$(am__dirstamp)
hash/gpuminer-KeccakSponge.$(OBJEXT): hash/$(am__dirstamp) \
	hash/$(DEPDIR)/$(am__dirstamp)
hash/gpuminer-skein_block.$(OBJEXT): hash/$(am__dirstamp) \
	hash/$(DEPDIR)/$(am__dirstamp)

gpuminer$(EXEEXT): $(gpuminer_OBJECTS) $(gpuminer_DEPENDENCIES) $(EXTRA_gpuminer_DEPENDENCIES) 
	@rm -f gpuminer$(EXEEXT)
	$(NVCC) -arch=sm_52 -dlink -o cuLink.o $(gpuminer_OBJECTS)
	$(AM_V_CXXLD)$(gpuminer_LINK) $(gpuminer_OBJECTS) cuLink.o $(gpuminer_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f cuda/*.$(OBJEXT)
	-rm -f hash/*.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/gpuminer-bigmath.Po
include ./$(DEPDIR)/gpuminer-iniParser.Po
include ./$(DEPDIR)/gpuminer-miner.Po
include ./$(DEPDIR)/gpuminer-prime.Po
include ./$(DEPDIR)/gpuminer-util.Po
include hash/$(DEPDIR)/gpuminer-Keccak-compact64.Po
include hash/$(DEPDIR)/gpuminer-KeccakDuplex.Po
include hash/$(DEPDIR)/gpuminer-KeccakHash.Po
include hash/$(DEPDIR)/gpuminer-KeccakSponge.Po
include hash/$(DEPDIR)/gpuminer-skein.Po
include hash/$(DEPDIR)/gpuminer-skein_block.Po

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CC)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LTCOMPILE) -c -o $@ $<

hash/gpuminer-KeccakDuplex.o: hash/KeccakDuplex.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hash/gpuminer-KeccakDuplex.o -MD -MP -MF hash/$(DEPDIR)/gpuminer-KeccakDuplex.Tpo -c -o hash/gpuminer-KeccakDuplex.o `test -f 'hash/KeccakDuplex.c' || echo '$(srcdir)/'`hash/KeccakDuplex.c
	$(AM_V_at)$(am__mv) hash/$(DEPDIR)/gpuminer-KeccakDuplex.Tpo hash/$(DEPDIR)/gpuminer-KeccakDuplex.Po
#	$(AM_V_CC)source='hash/KeccakDuplex.c' object='hash/gpuminer-KeccakDuplex.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hash/gpuminer-KeccakDuplex.o `test -f 'hash/KeccakDuplex.c' || echo '$(srcdir)/'`hash/KeccakDuplex.c

hash/gpuminer-KeccakDuplex.obj: hash/KeccakDuplex.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hash/gpuminer-KeccakDuplex.obj -MD -MP -MF hash/$(DEPDIR)/gpuminer-KeccakDuplex.Tpo -c -o hash/gpuminer-KeccakDuplex.obj `if test -f 'hash/KeccakDuplex.c'; then $(CYGPATH_W) 'hash/KeccakDuplex.c'; else $(CYGPATH_W) '$(srcdir)/hash/KeccakDuplex.c'; fi`
	$(AM_V_at)$(am__mv) hash/$(DEPDIR)/gpuminer-KeccakDuplex.Tpo hash/$(DEPDIR)/gpuminer-KeccakDuplex.Po
#	$(AM_V_CC)source='hash/KeccakDuplex.c' object='hash/gpuminer-KeccakDuplex.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hash/gpuminer-KeccakDuplex.obj `if test -f 'hash/KeccakDuplex.c'; then $(CYGPATH_W) 'hash/KeccakDuplex.c'; else $(CYGPATH_W) '$(srcdir)/hash/KeccakDuplex.c'; fi`

hash/gpuminer-Keccak-compact64.o: hash/Keccak-compact64.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hash/gpuminer-Keccak-compact64.o -MD -MP -MF hash/$(DEPDIR)/gpuminer-Keccak-compact64.Tpo -c -o hash/gpuminer-Keccak-compact64.o `test -f 'hash/Keccak-compact64.c' || echo '$(srcdir)/'`hash/Keccak-compact64.c
	$(AM_V_at)$(am__mv) hash/$(DEPDIR)/gpuminer-Keccak-compact64.Tpo hash/$(DEPDIR)/gpuminer-Keccak-compact64.Po
#	$(AM_V_CC)source='hash/Keccak-compact64.c' object='hash/gpuminer-Keccak-compact64.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hash/gpuminer-Keccak-compact64.o `test -f 'hash/Keccak-compact64.c' || echo '$(srcdir)/'`hash/Keccak-compact64.c

hash/gpuminer-Keccak-compact64.obj: hash/Keccak-compact64.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hash/gpuminer-Keccak-compact64.obj -MD -MP -MF hash/$(DEPDIR)/gpuminer-Keccak-compact64.Tpo -c -o hash/gpuminer-Keccak-compact64.obj `if test -f 'hash/Keccak-compact64.c'; then $(CYGPATH_W) 'hash/Keccak-compact64.c'; else $(CYGPATH_W) '$(srcdir)/hash/Keccak-compact64.c'; fi`
	$(AM_V_at)$(am__mv) hash/$(DEPDIR)/gpuminer-Keccak-compact64.Tpo hash/$(DEPDIR)/gpuminer-Keccak-compact64.Po
#	$(AM_V_CC)source='hash/Keccak-compact64.c' object='hash/gpuminer-Keccak-compact64.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hash/gpuminer-Keccak-compact64.obj `if test -f 'hash/Keccak-compact64.c'; then $(CYGPATH_W) 'hash/Keccak-compact64.c'; else $(CYGPATH_W) '$(srcdir)/hash/Keccak-compact64.c'; fi`

hash/gpuminer-KeccakHash.o: hash/KeccakHash.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hash/gpuminer-KeccakHash.o -MD -MP -MF hash/$(DEPDIR)/gpuminer-KeccakHash.Tpo -c -o hash/gpuminer-KeccakHash.o `test -f 'hash/KeccakHash.c' || echo '$(srcdir)/'`hash/KeccakHash.c
	$(AM_V_at)$(am__mv) hash/$(DEPDIR)/gpuminer-KeccakHash.Tpo hash/$(DEPDIR)/gpuminer-KeccakHash.Po
#	$(AM_V_CC)source='hash/KeccakHash.c' object='hash/gpuminer-KeccakHash.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hash/gpuminer-KeccakHash.o `test -f 'hash/KeccakHash.c' || echo '$(srcdir)/'`hash/KeccakHash.c

hash/gpuminer-KeccakHash.obj: hash/KeccakHash.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hash/gpuminer-KeccakHash.obj -MD -MP -MF hash/$(DEPDIR)/gpuminer-KeccakHash.Tpo -c -o hash/gpuminer-KeccakHash.obj `if test -f 'hash/KeccakHash.c'; then $(CYGPATH_W) 'hash/KeccakHash.c'; else $(CYGPATH_W) '$(srcdir)/hash/KeccakHash.c'; fi`
	$(AM_V_at)$(am__mv) hash/$(DEPDIR)/gpuminer-KeccakHash.Tpo hash/$(DEPDIR)/gpuminer-KeccakHash.Po
#	$(AM_V_CC)source='hash/KeccakHash.c' object='hash/gpuminer-KeccakHash.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hash/gpuminer-KeccakHash.obj `if test -f 'hash/KeccakHash.c'; then $(CYGPATH_W) 'hash/KeccakHash.c'; else $(CYGPATH_W) '$(srcdir)/hash/KeccakHash.c'; fi`

hash/gpuminer-KeccakSponge.o: hash/KeccakSponge.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hash/gpuminer-KeccakSponge.o -MD -MP -MF hash/$(DEPDIR)/gpuminer-KeccakSponge.Tpo -c -o hash/gpuminer-KeccakSponge.o `test -f 'hash/KeccakSponge.c' || echo '$(srcdir)/'`hash/KeccakSponge.c
	$(AM_V_at)$(am__mv) hash/$(DEPDIR)/gpuminer-KeccakSponge.Tpo hash/$(DEPDIR)/gpuminer-KeccakSponge.Po
#	$(AM_V_CC)source='hash/KeccakSponge.c' object='hash/gpuminer-KeccakSponge.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hash/gpuminer-KeccakSponge.o `test -f 'hash/KeccakSponge.c' || echo '$(srcdir)/'`hash/KeccakSponge.c

hash/gpuminer-KeccakSponge.obj: hash/KeccakSponge.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT hash/gpuminer-KeccakSponge.obj -MD -MP -MF hash/$(DEPDIR)/gpuminer-KeccakSponge.Tpo -c -o hash/gpuminer-KeccakSponge.obj `if test -f 'hash/KeccakSponge.c'; then $(CYGPATH_W) 'hash/KeccakSponge.c'; else $(CYGPATH_W) '$(srcdir)/hash/KeccakSponge.c'; fi`
	$(AM_V_at)$(am__mv) hash/$(DEPDIR)/gpuminer-KeccakSponge.Tpo hash/$(DEPDIR)/gpuminer-KeccakSponge.Po
#	$(AM_V_CC)source='hash/KeccakSponge.c' object='hash/gpuminer-KeccakSponge.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o hash/gpuminer-KeccakSponge.obj `if test -f 'hash/KeccakSponge.c'; then $(CYGPATH_W) 'hash/KeccakSponge.c'; else $(CYGPATH_W) '$(srcdir)/hash/KeccakSponge.c'; fi`

.cpp.o:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cpp.lo:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CXX)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LTCXXCOMPILE) -c -o $@ $<

gpuminer-bigmath.o: bigmath.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT gpuminer-bigmath.o -MD -MP -MF $(DEPDIR)/gpuminer-bigmath.Tpo -c -o gpuminer-bigmath.o `test -f 'bigmath.cpp' || echo '$(srcdir)/'`bigmath.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/gpuminer-bigmath.Tpo $(DEPDIR)/gpuminer-bigmath.Po
#	$(AM_V_CXX)source='bigmath.cpp' object='gpuminer-bigmath.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o gpuminer-bigmath.o `test -f 'bigmath.cpp' || echo '$(srcdir)/'`bigmath.cpp

gpuminer-bigmath.obj: bigmath.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT gpuminer-bigmath.obj -MD -MP -MF $(DEPDIR)/gpuminer-bigmath.Tpo -c -o gpuminer-bigmath.obj `if test -f 'bigmath.cpp'; then $(CYGPATH_W) 'bigmath.cpp'; else $(CYGPATH_W) '$(srcdir)/bigmath.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/gpuminer-bigmath.Tpo $(DEPDIR)/gpuminer-bigmath.Po
#	$(AM_V_CXX)source='bigmath.cpp' object='gpuminer-bigmath.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o gpuminer-bigmath.obj `if test -f 'bigmath.cpp'; then $(CYGPATH_W) 'bigmath.cpp'; else $(CYGPATH_W) '$(srcdir)/bigmath.cpp'; fi`

gpuminer-miner.o: miner.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT gpuminer-miner.o -MD -MP -MF $(DEPDIR)/gpuminer-miner.Tpo -c -o gpuminer-miner.o `test -f 'miner.cpp' || echo '$(srcdir)/'`miner.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/gpuminer-miner.Tpo $(DEPDIR)/gpuminer-miner.Po
#	$(AM_V_CXX)source='miner.cpp' object='gpuminer-miner.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o gpuminer-miner.o `test -f 'miner.cpp' || echo '$(srcdir)/'`miner.cpp

gpuminer-miner.obj: miner.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT gpuminer-miner.obj -MD -MP -MF $(DEPDIR)/gpuminer-miner.Tpo -c -o gpuminer-miner.obj `if test -f 'miner.cpp'; then $(CYGPATH_W) 'miner.cpp'; else $(CYGPATH_W) '$(srcdir)/miner.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/gpuminer-miner.Tpo $(DEPDIR)/gpuminer-miner.Po
#	$(AM_V_CXX)source='miner.cpp' object='gpuminer-miner.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o gpuminer-miner.obj `if test -f 'miner.cpp'; then $(CYGPATH_W) 'miner.cpp'; else $(CYGPATH_W) '$(srcdir)/miner.cpp'; fi`

gpuminer-prime.o: prime.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT gpuminer-prime.o -MD -MP -MF $(DEPDIR)/gpuminer-prime.Tpo -c -o gpuminer-prime.o `test -f 'prime.cpp' || echo '$(srcdir)/'`prime.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/gpuminer-prime.Tpo $(DEPDIR)/gpuminer-prime.Po
#	$(AM_V_CXX)source='prime.cpp' object='gpuminer-prime.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o gpuminer-prime.o `test -f 'prime.cpp' || echo '$(srcdir)/'`prime.cpp

gpuminer-prime.obj: prime.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT gpuminer-prime.obj -MD -MP -MF $(DEPDIR)/gpuminer-prime.Tpo -c -o gpuminer-prime.obj `if test -f 'prime.cpp'; then $(CYGPATH_W) 'prime.cpp'; else $(CYGPATH_W) '$(srcdir)/prime.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/gpuminer-prime.Tpo $(DEPDIR)/gpuminer-prime.Po
#	$(AM_V_CXX)source='prime.cpp' object='gpuminer-prime.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o gpuminer-prime.obj `if test -f 'prime.cpp'; then $(CYGPATH_W) 'prime.cpp'; else $(CYGPATH_W) '$(srcdir)/prime.cpp'; fi`

gpuminer-util.o: util.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT gpuminer-util.o -MD -MP -MF $(DEPDIR)/gpuminer-util.Tpo -c -o gpuminer-util.o `test -f 'util.cpp' || echo '$(srcdir)/'`util.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/gpuminer-util.Tpo $(DEPDIR)/gpuminer-util.Po
#	$(AM_V_CXX)source='util.cpp' object='gpuminer-util.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o gpuminer-util.o `test -f 'util.cpp' || echo '$(srcdir)/'`util.cpp

gpuminer-util.obj: util.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT gpuminer-util.obj -MD -MP -MF $(DEPDIR)/gpuminer-util.Tpo -c -o gpuminer-util.obj `if test -f 'util.cpp'; then $(CYGPATH_W) 'util.cpp'; else $(CYGPATH_W) '$(srcdir)/util.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/gpuminer-util.Tpo $(DEPDIR)/gpuminer-util.Po
#	$(AM_V_CXX)source='util.cpp' object='gpuminer-util.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o gpuminer-util.obj `if test -f 'util.cpp'; then $(CYGPATH_W) 'util.cpp'; else $(CYGPATH_W) '$(srcdir)/util.cpp'; fi`

gpuminer-iniParser.o: iniParser.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT gpuminer-iniParser.o -MD -MP -MF $(DEPDIR)/gpuminer-iniParser.Tpo -c -o gpuminer-iniParser.o `test -f 'iniParser.cpp' || echo '$(srcdir)/'`iniParser.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/gpuminer-iniParser.Tpo $(DEPDIR)/gpuminer-iniParser.Po
#	$(AM_V_CXX)source='iniParser.cpp' object='gpuminer-iniParser.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o gpuminer-iniParser.o `test -f 'iniParser.cpp' || echo '$(srcdir)/'`iniParser.cpp

gpuminer-iniParser.obj: iniParser.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT gpuminer-iniParser.obj -MD -MP -MF $(DEPDIR)/gpuminer-iniParser.Tpo -c -o gpuminer-iniParser.obj `if test -f 'iniParser.cpp'; then $(CYGPATH_W) 'iniParser.cpp'; else $(CYGPATH_W) '$(srcdir)/iniParser.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/gpuminer-iniParser.Tpo $(DEPDIR)/gpuminer-iniParser.Po
#	$(AM_V_CXX)source='iniParser.cpp' object='gpuminer-iniParser.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o gpuminer-iniParser.obj `if test -f 'iniParser.cpp'; then $(CYGPATH_W) 'iniParser.cpp'; else $(CYGPATH_W) '$(srcdir)/iniParser.cpp'; fi`

hash/gpuminer-skein.o: hash/skein.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hash/gpuminer-skein.o -MD -MP -MF hash/$(DEPDIR)/gpuminer-skein.Tpo -c -o hash/gpuminer-skein.o `test -f 'hash/skein.cpp' || echo '$(srcdir)/'`hash/skein.cpp
	$(AM_V_at)$(am__mv) hash/$(DEPDIR)/gpuminer-skein.Tpo hash/$(DEPDIR)/gpuminer-skein.Po
#	$(AM_V_CXX)source='hash/skein.cpp' object='hash/gpuminer-skein.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hash/gpuminer-skein.o `test -f 'hash/skein.cpp' || echo '$(srcdir)/'`hash/skein.cpp

hash/gpuminer-skein.obj: hash/skein.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hash/gpuminer-skein.obj -MD -MP -MF hash/$(DEPDIR)/gpuminer-skein.Tpo -c -o hash/gpuminer-skein.obj `if test -f 'hash/skein.cpp'; then $(CYGPATH_W) 'hash/skein.cpp'; else $(CYGPATH_W) '$(srcdir)/hash/skein.cpp'; fi`
	$(AM_V_at)$(am__mv) hash/$(DEPDIR)/gpuminer-skein.Tpo hash/$(DEPDIR)/gpuminer-skein.Po
#	$(AM_V_CXX)source='hash/skein.cpp' object='hash/gpuminer-skein.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hash/gpuminer-skein.obj `if test -f 'hash/skein.cpp'; then $(CYGPATH_W) 'hash/skein.cpp'; else $(CYGPATH_W) '$(srcdir)/hash/skein.cpp'; fi`

hash/gpuminer-skein_block.o: hash/skein_block.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hash/gpuminer-skein_block.o -MD -MP -MF hash/$(DEPDIR)/gpuminer-skein_block.Tpo -c -o hash/gpuminer-skein_block.o `test -f 'hash/skein_block.cpp' || echo '$(srcdir)/'`hash/skein_block.cpp
	$(AM_V_at)$(am__mv) hash/$(DEPDIR)/gpuminer-skein_block.Tpo hash/$(DEPDIR)/gpuminer-skein_block.Po
#	$(AM_V_CXX)source='hash/skein_block.cpp' object='hash/gpuminer-skein_block.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hash/gpuminer-skein_block.o `test -f 'hash/skein_block.cpp' || echo '$(srcdir)/'`hash/skein_block.cpp

hash/gpuminer-skein_block.obj: hash/skein_block.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT hash/gpuminer-skein_block.obj -MD -MP -MF hash/$(DEPDIR)/gpuminer-skein_block.Tpo -c -o hash/gpuminer-skein_block.obj `if test -f 'hash/skein_block.cpp'; then $(CYGPATH_W) 'hash/skein_block.cpp'; else $(CYGPATH_W) '$(srcdir)/hash/skein_block.cpp'; fi`
	$(AM_V_at)$(am__mv) hash/$(DEPDIR)/gpuminer-skein_block.Tpo hash/$(DEPDIR)/gpuminer-skein_block.Po
#	$(AM_V_CXX)source='hash/skein_block.cpp' object='hash/gpuminer-skein_block.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(gpuminer_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o hash/gpuminer-skein_block.obj `if test -f 'hash/skein_block.cpp'; then $(CYGPATH_W) 'hash/skein_block.cpp'; else $(CYGPATH_W) '$(srcdir)/hash/skein_block.cpp'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) gpuminer-config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f cuda/$(DEPDIR)/$(am__dirstamp)
	-rm -f cuda/$(am__dirstamp)
	-rm -f hash/$(DEPDIR)/$(am__dirstamp)
	-rm -f hash/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libtool mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR) hash/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR) hash/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-cscope clean-generic clean-libtool \
	cscope cscopelist-am ctags ctags-am dist dist-all dist-bzip2 \
	dist-gzip dist-lzip dist-shar dist-tarZ dist-xz dist-zip \
	distcheck distclean distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags tags-am uninstall uninstall-am uninstall-binPROGRAMS

.PRECIOUS: Makefile

*cu.o:

# we're now targeting all major compute architectures within one binary.
cuda/sieve.o:	cuda/sieve.cu cuda/cuda.h cuda/frame_resources.h
	$(NVCC) -std=c++11 -g -O2 -D_FORCE_INLINES -I . -Xptxas "-v" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --maxrregcount=80 --ptxas-options=-v -o $@ -c $<

cuda/fermat.o: cuda/fermat.cu cuda/fermat.h cuda/frame_resources.h
	$(NVCC) -std=c++11 -g -O2 -D_FORCE_INLINES -I . -rdc=true -Xptxas "-v" -gencode=arch=compute_35,code=\"sm_35,compute_35\" -gencode=arch=compute_52,code=\"sm_52,compute_52\" --maxrregcount=128 --ptxas-options=-v -o $@ -c $<

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
